### ISSUE TITLE
There is space in the output links

### ISSUE THREAD

**Issue by Sh4d0wHunt3rX** [projectdiscovery/katana#1001]
Hi. This is my command:

```
katana -u 'https://sftp1.massmart.co.za/' -d 2 -headless --no-sandbox -jc -jsl -aff -kf all -cos feed,css,mailto,fnt,ogg,css,jpg,jpeg,png,svg,img,gif,exe,mp4,flv,pdf,doc,ogv,webm,wmv,webp,mov,mp3,m4a,m4p,ppt,pptx,scss,tif,tiff,ttf,otf,woff,woff2,bmp,ico,eot,htc,swf,rtf,image,rf,txt,ml,ip -fdc 'status_code == 404' -silent
```

And as you can see, in some links there are space:

![image](https://github.com/user-attachments/assets/e5c6c3bc-b217-49b6-b9eb-a0f14c0c0d3e)

**Comment by dogancanbakir** [comment]
I couldn't reproduce it. Are you still experiencing the issue?

**Comment by Sh4d0wHunt3rX** [comment]
Unfortunately that link is not available anymore, I will re open this if I encountered again.
