### ISSUE TITLE
adding -irr (-include-response) and -irrb (-include-response-base64) flags look like httpx for saving raw req/res in json output

### ISSUE THREAD

**Issue by Bugerox** [projectdiscovery/katana#1014]
## Httpx Output Flags:
![image](https://github.com/user-attachments/assets/e3129a10-85e4-4772-924b-f4e1a5e19e7d)

## Katana Output Flags
![image](https://github.com/user-attachments/assets/886c90e3-5d72-4ebd-9ff6-192278401a11)

sample output with -irrb flag (httpx):
```
echo google.com | httpx -j -irrb -silent | jq .
```
![image](https://github.com/user-attachments/assets/0f2d027a-767a-42be-8ec2-adfc4bc95ed2)

these two flags is very useful in pentest/bug bounty process. please add these flags

**Comment by GeorginaReeder** [comment]
Thanks so much for your feature request @Bugerox , we'll take a look into it!

**Comment by Bugerox** [comment]
thanks for your attention @GeorginaReeder

**Comment by Bugerox** [comment]
no i want switches like httpx, base64 by default
