### ISSUE TITLE
Hide out of scope items

### ISSUE THREAD

**Issue by znadir** [projectdiscovery/katana#1080]
### Please describe your feature request:

Instead of hiding external endpoint from scoped crawling by default, hide only out of scope endpoints. 

### Describe the use case of this feature:

Would be useful to hide out of scope items, not only external endpoints.

**Comment by znadir** [comment]
I dont know if I'm clear. let's say i use -cos option to add out of scope endpoints, it doesn't hide them from output

**Comment by GeorginaReeder** [comment]
Thanks for your feature request @znadir , we'll take a look into this!

**Comment by dogancanbakir** [comment]
@znadir Thanks for opening the issue. I couldn't repro the issue; I compared the following two CMDs, and I found that `-cos` is working as expected:

`
katana -u https://projectdiscovery.io -o output.txt
`

`
katana -u https://projectdiscovery.io -cos _next -o output1.txt
`

Also, make sure it's the latest version.

**Comment by dogancanbakir** [comment]
Closing this. Feel free to reopen if the issue persists.
