### ISSUE TITLE
Passive Scan :(

### ISSUE THREAD

**Issue by Dark-Aura** [projectdiscovery/katana#1081]
Hi Team

I noticed that in the latest update v1.1.1, the passive scan feature was removed. I was wondering why you made that decision. 

![Image](https://github.com/user-attachments/assets/05c8e081-d423-4144-9180-4399b3b33f6e)

![Image](https://github.com/user-attachments/assets/a351b365-5c9b-45c8-a4c9-ff0334c8c985)

**Comment by dogancanbakir** [comment]
Reason: https://github.com/projectdiscovery/katana/pull/899#issuecomment-2125428173
