### ISSUE TITLE
Katana fails to run after update on MacBook pro m1.

### ISSUE THREAD

**Issue by davisbug** [projectdiscovery/katana#1095]
### katana version:

- command cannot run 
![Image](https://github.com/user-attachments/assets/55dcde27-9554-4a80-8632-5db7691afcc3)

### Current Behavior:

- updated katana  using below command. After the update katana failed to start, keeps crashing.
```bash
CGO_ENABLED=1 go install github.com/projectdiscovery/katana/cmd/katana@latest
```
- go version
 `go version go1.22.3 darwin/arm64`

- go env
![Image](https://github.com/user-attachments/assets/05d4ae5d-8ed6-4d69-9461-5880d8b6db6a)

### Expected Behavior:

- Expected to function normally.

**Comment by dogancanbakir** [comment]
Trying to understand:
What was the previous version both `katana` and `go` ? 
How did you install it previously?
Could you remove it and retry with `go install github.com/projectdiscovery/katana/cmd/katana@latest?` ?
