### ISSUE TITLE
installation error: package X is not in GOROOT

### ISSUE THREAD

**Issue by ara735** [projectdiscovery/katana#1121]
CGO_ENABLED=1 go install github.com/projectdiscovery/katana/cmd/katana@latest
/root/go/pkg/mod/github.com/gaissmai/bart@v0.9.5/node.go:7:2: package cmp is not in GOROOT (/usr/src/cmp)
/root/go/pkg/mod/github.com/refraction-networking/utls@v1.6.7/cfkem.go:25:2: package crypto/ecdh is not in GOROOT (/usr/src/crypto/ecdh)
/root/go/pkg/mod/github.com/projectdiscovery/utils@v0.3.1-0.20241201132332-cebafa101965/errkit/errors.go:9:2: package log/slog is not in GOROOT (/usr/src/log/slog)
/root/go/pkg/mod/github.com/gaissmai/bart@v0.9.5/jsonify.go:9:2: package slices is not in GOROOT (/usr/src/slices)

**Comment by dogancanbakir** [comment]
Could you share the output of the `go version`?

**Comment by dogancanbakir** [comment]
Closing this. Feel free to reopen if the issue persists.
