### ISSUE TITLE
can't crawl tesla.com; context deadline exceeded

### ISSUE THREAD

**Issue by kanXer** [projectdiscovery/katana#1130]
![Image](https://github.com/user-attachments/assets/196508d1-b015-4cce-a2df-3db5052ac4b6)

**Comment by Eytes** [comment]
Hi, @kanXer!

Is there any progress?

**Comment by kanXer** [comment]
No seem like they have implemented anti-scraping or bot detection because its works on other websites.

**Comment by whiteBIGcat** [comment]
Yep, it didn't work on upwork.com either
