### ISSUE TITLE
Please add an example using katana as library in other go code.

### ISSUE THREAD

**Issue by zaqqaza** [projectdiscovery/katana#134]
Hello!
 it looks like the katana tool put its runner in an internal directory meaning folks couldn't use it to integrate katana into their own Go code. Is there any chance of this changing in the future?

**Comment by derekperkins** [comment]
Very interested in this

**Comment by ehsandeep** [comment]
@zaqqaza @derekperkins this is now added into `dev` branch https://github.com/projectdiscovery/katana/tree/dev#katana-as-a-library
