### ISSUE TITLE
Support TLS ClientHello randomization

### ISSUE THREAD

**Issue by moonD4rk** [projectdiscovery/katana#136]
### Please describe your feature request:

```
   -tlsi, -tls-impersonate  enable experimental client hello (ja3) tls randomization
```

See below for the implementation
- https://github.com/projectdiscovery/fastdialer/issues/123
- https://github.com/projectdiscovery/httpx/pull/1199

### Describe the use case of this feature:
To avoid detection/blocking from [Cloudflare](https://developers.cloudflare.com/bots/concepts/ja3-fingerprint/) and [Akamai](https://www.akamai.com/blog/security/bots-tampering-with-tls-to-avoid-detection) based on JA3 fingerprint.

**Comment by ehsandeep** [comment]
@moonD4rk I've updated the issue according to the latest development. To start with this **experimental** feature, it will optionally support client hello randomization, and later in the future, we will look to support specific client hello to use.

This is feature is now added in httpx - https://github.com/projectdiscovery/httpx/pull/1199 and the same will be done for other pd projects including katana.

**Comment by Mzack9999** [comment]
Note: headless native crawler doesn't need this since chrome already randomize TLS extensions part internally

**Comment by ehsandeep** [comment]
@Mzack9999 this support in now added in the latest release (`-tlsi`) option.
