### ISSUE TITLE
Cannot install in macOS Ventura 13.0

### ISSUE THREAD

**Issue by Masriyan** [projectdiscovery/katana#148]
Hi 

i'm having issue when trying installing  katana latest version in macOS ventura 13.0 with error message below

### katana version:
installation with go install , latest version 

error message :
# github.com/projectdiscovery/katana/cmd/katana
ld: warning: -no_pie is deprecated when targeting new OS versions
ld: warning: non-standard -pagezero_size is deprecated when targeting macOS 13.0 or later

<img width="573" alt="Screenshot 2022-11-09 at 8 37 24 AM" src="https://user-images.githubusercontent.com/15161949/200715381-96b87059-84f8-4803-8b01-26d8590581a9.png">

**Comment by ehsandeep** [comment]
@Masriyan 

```console
GOFLAGS="-buildmode=pie" go install github.com/projectdiscovery/katana/cmd/katana@latest
```
