### ISSUE TITLE
katana consuming all CPU?

### ISSUE THREAD

**Issue by marcelo321** [projectdiscovery/katana#159]
### katana version:
[INF] Current version: v0.0.1

### Steps To Reproduce:

So katana is consuming absolutely all CPU and like "killing" all other processes because it leaves no cpu for other processes. Is this normal or there is a way to control this? I am not using any special flags or headless, so shouldn't be this crazy..?

![image](https://user-images.githubusercontent.com/29487296/201001984-673f94cd-2e8f-4aac-9a28-f5157e562587.png)

If there is a way to have this under control please let me know. the most similar tool to this would be hakrawler, which doesn't consume much cpu/ram at all (afaik).

**Comment by ehsandeep** [comment]
@marcelo321 how big is the URL list? Also what are the CPU specification of your machine?

**Comment by marcelo321** [comment]
Hi @ehsandeep,

So this is happening constantly when doing something like `echo host.com | waybackurls | katana optionshere`

I am using a pretty big VPS (8GB RAM and 4CPU), but I assume most people rely on more cheaper VPS options.

My doubts is it has something to do with javascript parsing/reading files.

Check with the following example:

`echo zonduu.me | waybackurls | katana -jc -timeout 7 -ct 240 -d 3 -aff -kf all -p 5 -c 3`

the site zonduu.me is my site that is hosted in github with little to no directories/files, so should be a light crawl.. but it will consume all CPU of your vps/machine.

If you run `katana` without any flags then it runs ok, so it has something to do either with `-jc` or `-aff` or `-kf all`

**Comment by ayoubackup** [comment]
i have same issues i use OS windows server 16 GB and all my cpu used 

![issCapture](https://user-images.githubusercontent.com/57925216/202577035-08ce18f2-2134-48d1-a0c0-345fdca40d34.PNG)

**Comment by marcelo321** [comment]
yeah @ayoubackup. Doesn't matter the OS/cpu you have, katana will use it all to achieve max speed. The problem is if you actually run other things simultaneously with katana, or after running katana. added `-p 4 `-c 4` or lower and helps, but still the same regarding cpu.

**Comment by ehsandeep** [comment]
@marcelo321 thanks for reporting this, this is now fixed in dev branch with https://github.com/projectdiscovery/katana/pull/362
