### ISSUE TITLE
"proxy" option is not passed to headless browser

### ISSUE THREAD

**Issue by z7701858** [projectdiscovery/katana#166]
Passive scanner not receiving traffic from katana when `-hl -sc` is enabled
![image](https://user-images.githubusercontent.com/32709921/201312648-f8b22f5b-14f4-4096-b2bd-877a78932855.png)
![image](https://user-images.githubusercontent.com/32709921/201312700-53c34f33-675f-4de9-95a7-24186306abfc.png)
Passive scanner receives traffic from katana when `-hl -sc` is not enabled
![image](https://user-images.githubusercontent.com/32709921/201312961-4422f075-6fdb-42a1-8a8d-256362cf4718.png)
![image](https://user-images.githubusercontent.com/32709921/201312881-49eda98a-932c-41f1-b456-2d18a03a876b.png)

system browser is google-chrome from https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb and open `--no-sandbox`

**Comment by ehsandeep** [comment]
@z7701858 if you are already on the latest version i.e v0.0.2, here is workaround

```console
katana -u http://testphp.vulnweb.com -hl -sc -ho proxy-server=http://127.0.0.1:7777
```
