### ISSUE TITLE
Add Support for Dynamic Websites

### ISSUE THREAD

**Issue by laurancelo** [projectdiscovery/katana#192]
### Please describe your feature request:
add support for dynamic websites build with modern frontend frameworks, such as AngularJS, React and Vue.js

### Describe the use case of this feature:
current version of katana is unable to process these dynamic contents.

**Comment by ehsandeep** [comment]
@laurancelo thank you, we have a ticket for this - https://github.com/projectdiscovery/katana/issues/63
