### ISSUE TITLE
`store-response` to support in headless mode

### ISSUE THREAD

**Issue by rohitcoder** [projectdiscovery/katana#217]
Follow up ticket for - https://github.com/projectdiscovery/katana/issues/177

### Please describe your feature request:

Having a feature to extract all requests from browser will be best, i have been using https://github.com/Qianlitp/crawlergo i want something like this, but crawlergo have some issues like, we can't add our own "playwright / selenium scripts" (Let's suppose, we want to do automatic login?) , 

If we can have something like which extracts all XHR stores them somewhere and also removes duplicate or same kind of requests like https://api.website.com/user/1, https://api.website.com/user/1

I wasn't able to find any tool which can help me.

### Describe the use case of this feature:
1. Can be used in making Custom DAST Solutions (Kind of burp scanner / or zap )
2. Can be used in IDOR Discovery by automating some parts
3. Can be used in mapping Target's structure

**Comment by gister9000** [comment]
Is there ETA for this one?

**Comment by gister9000** [comment]
@rohitcoder there are plenty of solutions to filter similar URLs
https://github.com/rotemreiss/uddup
https://blog.bytebytego.com/p/how-to-avoid-crawling-duplicate-urls
