### ISSUE TITLE
Installation error on kali OS

### ISSUE THREAD

**Issue by abhijithpa** [projectdiscovery/katana#218]
when installing katana with go install github.com/projectdiscovery/katana/cmd/katana@latest it produces an error

asm: open go/pkg/mod/github.com/modern-go/reflect2@v1.0.2/reflect2_amd64.s: no such file or directory

**Comment by ehsandeep** [comment]
@abhijithpa Can you also include details of your system/OS/arch?

**Comment by abhijithpa** [comment]
Name="Kali GNU/Linux"
Version="2022.4"
Go version=go version go1.19.3 linux/amd64

**Comment by 0xSebin** [comment]
Even i have the same issue.

**Comment by Mzack9999** [comment]
I'm unable to reproduce it. I just tried on a fresh install of the latest Kali Linux:
```console
$ sudo apt install golang
$ go env                                                         
...
GOARCH="amd64"
GOVERSION="go1.19.4"
$ go install github.com/projectdiscovery/katana/cmd/katana@latest
go: downloading github.com/projectdiscovery/katana v0.0.2
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/projectdiscovery/goflags v0.1.3
...
$
```
Could you try to update to `go1.19.4`?

**Comment by abhijithpa** [comment]
Actually upgrading to go1.19.4 fixed the issue for me.

**Comment by Mzack9999** [comment]
@abhijithpa Thanks for confirming - I'm closing the issue as complete
