### ISSUE TITLE
HELP INSTALL PROBLEM

### ISSUE THREAD

**Issue by ringawy** [projectdiscovery/katana#252]
try install katana by go version 19.3 it download few folder and try to run katana don't work
then try to update go to 19.4 after update try install katana again but i have this problem 

─$ go install github.com/projectdiscovery/katana/cmd/katana@latest
go/pkg/mod/github.com/tklauser/go-sysconf@v0.3.10/example_test.go:1:1: expected 'package', found 'EOF'
go/pkg/mod/github.com/ysmood/goob@v0.4.0/examples_test.go:1:1: expected 'package', found 'EOF'

─$ go version                                                                                                                             127 ⨯
go version go1.19.4 linux/amd64

─$ go env                                                                                                                                 130 ⨯
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/maxemos/.cache/go-build"
GOENV="/home/maxemos/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/maxemos/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/maxemos/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.19"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.19/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4190575152=/tmp/go-build -gno-record-gcc-switches"

**Comment by Mzack9999** [comment]
@ringawy I just tried on a fresh ubuntu install, and everything works as expected. Which Linux Distribution are you using? Have you tried to prune the go cache?

```console
$ go ​clean -modcache
```
