### ISSUE TITLE
Support for customizable example field-config file

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/katana#286]
### Please describe your feature request:
As of now default field-config file gets created at `~/.config/katana/field-config.yaml` upon the first run, instead of using static and [hardcoded example from code](https://github.com/projectdiscovery/katana/blob/ffc61b8df34555b4ad7ea800a9fd642a2a734af6/pkg/output/custom_field.go#L39), an example `field-config.yaml` can be placed at the root of the project and used to create default `field-config.yaml` file at `~/.config/katana/` upon installation.

### Describe the use case of this feature:
- Visible custom rules (field)
- Allows others to share / add / update new custom fields.
    - https://twitter.com/N7WEra/status/1615411951957381130 
    - https://twitter.com/ReconOne_bk/status/1616787402319708164

**Comment by brenocss** [comment]
https://github.com/projectdiscovery/katana/issues/143 Would be great if we handle this like nuclei-templates, that we share our formFilling.yaml and fieldConfig.yaml

**Comment by ehsandeep** [comment]
For context - https://github.com/projectdiscovery/katana/pull/318#issuecomment-1471605424
