### ISSUE TITLE
context deadline exceeded while using burp proxy

### ISSUE THREAD

**Issue by MuhammadUsman-coder** [projectdiscovery/katana#295]
## Command giving error 
 - `katana -u 'https://www.atg.se/' -d 8 -jc -kf all -timeout 60 -aff -rl 5 -o atgkatana.txt   -v  -proxy http://127.0.0.1:8080 -hl -sc  --no-sandbox`

Error : 
```
[WRN] Could not parse known files for https://www.atg.se/: could not parse sitemap: could not decode xml: XML syntax error on line 23: invalid character entity &nbsp;

[WRN] "https://www.atg.se/" on wait load: context deadline exceeded
[WRN] "https://www.atg.se/" on wait idle: context deadline exceeded
[WRN] Could not request seed URL: could not get dom: context deadline exceeded
```
- Screenshot
![image](https://user-images.githubusercontent.com/54319802/216821206-246abcbb-3110-4a30-a37d-ff96ca3e8978.png)

## Command without burp proxy
- `katana -u 'https://www.atg.se/' -d 8 -jc -kf all -timeout 60 -aff -rl 5 -o atgkatana.txt   -v  -hl -sc  --no-sandbox`

Results:
![image](https://user-images.githubusercontent.com/54319802/216821189-ad363cd4-c768-43f9-970f-e44a120cce09.png)

Burp is running correctly with proxy listening on 8080 port .

**Comment by MuhammadUsman-coder** [comment]
Moreoever i do recieves these three requests on burp proxy and the response is alright too here  when i run the command which gives error : 

![image](https://user-images.githubusercontent.com/54319802/216821309-d1cb9ac3-42ee-44dd-bcf8-5a3fdb4b3888.png)

**Comment by ehsandeep** [comment]
@MuhammadUsman-coder see https://github.com/projectdiscovery/katana/discussions/165#discussioncomment-4117623

**Comment by MuhammadUsman-coder** [comment]
Hi @eshadeep , i tried doing that but it did not work. 
i turn off http2 default from both the proxy and project setting and did not work.

You can check yourself too.

**Comment by ehsandeep** [comment]
@MuhammadUsman-coder this is known issue with using burp across many tools, for more context and original issue where this is being tracked - https://github.com/projectdiscovery/katana/issues/170
