### ISSUE TITLE
Include url response body in the callback function OnResult.

### ISSUE THREAD

**Issue by fetlife1** [projectdiscovery/katana#360]
Would be nice to have http response body in the callback response, for example as a `ReponseBody` field in the `Result` struct
```
 OnResult: func(result output.Result) { // Callback function to execute for result 
      fmt.Printf("respone body is %s\n",result.ResponseBody)    
    },    
  } 
```
Use case: Useful for scanning the website's html code without having to the request the same url again for example looking for secrets or running a regex across all found endpoitns, saving time and resources for the developer, and http response is probably laying around in some variable, might as well make use of it :)

**Comment by ehsandeep** [comment]
@fetlife1 this will be possible with https://github.com/projectdiscovery/katana/pull/312
