### ISSUE TITLE
-do not working

### ISSUE THREAD

**Issue by darshanpjpt** [projectdiscovery/katana#386]
-do option is no longet working in latest release.

katana -do -u http://testphp.vulnweb.com

![Screenshot from 2023-03-27 23-03-42](https://user-images.githubusercontent.com/71147956/228021100-5ba5269b-13e8-4a41-9586-bd57531d1627.png)

**Comment by ehsandeep** [comment]
Thank you @darshanpjpt for reporting this, this is now fixed in dev version with https://github.com/projectdiscovery/katana/pull/387

**Comment by ehsandeep** [comment]
@darshanpjpt this is now fixed in latest release, thanks for reporting.
