### ISSUE TITLE
Something wrong with the demo of 'Katana as a library' in readme

### ISSUE THREAD

**Issue by Co5mos** [projectdiscovery/katana#388]
Katana as a library: line 17:

result.URL undefined (type output.Result has no field or method URL)

### katana version:

v1.0.0

**Comment by niudaii** [comment]
Something wrong with the demo of 'Katana as a library' in readme.
demo options should add `Timeout: 10` or 
types.NewCrawlerOptions func to check zero and set a default value.
![image](https://user-images.githubusercontent.com/41844046/234454088-ce7fd619-e617-4960-87ed-bd4b10d89e56.png)
