### ISSUE TITLE
Support automatic probing when url scheme is not provided

### ISSUE THREAD

**Issue by 0xh7ml** [projectdiscovery/katana#392]
Support for automatic URL probing using **[httpx](https://github.com/projectdiscovery/httpx)** integration for dns input, this feature can be **supported as default** and optionally allow the users to disable it.

```console
   -dap, -disable-auto-probe          disable automatic probing with dns input
```

## Current behavior:

`$ katana -u google.com`

=> Didn't work / no response

`$ katan -u https://google.com`

=> Work fine

## After this change: 

`$ katana -u google.com` will work as well.

**Comment by ehsandeep** [comment]
@0xh7ml this is now fixed in latest release, thanks for reporting.
