### ISSUE TITLE
Support for path based cralwing

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/katana#417]
### Please describe your feature request:
Option to seed additional path with default crawling or only crawling seed input.

```console
   -path string  path or list of paths to use for fuzzing and crawling paths (comma-separated, file)
   -ddc  -disable-default-crawl disable default automatic crawling
```

### Describe the use case of this feature:
To perform more specific / known path-based crawling or crawl known paths on target/internet.

```console
$ katana -list targets.txt -path /app.js -ddc
```

**Comment by Mzack9999** [comment]
Closing as not planned - The functionality is better handled via `httpx | katana` piping

**Comment by nullenc0de** [comment]
Question regarding the utilization of httpx for targeted path-based crawling in Katana. If we input predefined paths into katana using httpx, will it conduct a complete recrawl of the entire site for each specified endpoint?

For instance, if we use httpx to identify paths such as /user, /admin, /xyz (using the command httpx -paths endpoints.txt), and then feed this output into Katana. Will Katana navigate to each endpoint, crawl the content under /admin along with the entire site, then proceed to /user and crawl its content along with the entire site, and similarly for /xyz?
