### ISSUE TITLE
Customizable json output to reduce file size / Omit raw / body

### ISSUE THREAD

**Issue by maik-s** [projectdiscovery/katana#447]
### Please describe your feature request:

Katana already allows customizing the output.
However, this does not apply to the json output format.
Currently, Katana always dumps the whole response into the JSON file **both** in raw and parsed.
Thereby, the json file is getting very enormous in size quickly.

I propose the following parameters, to reduce the file size:
1. `--omit-raw`:  Omit both raw request and raw response from the (json)-output
2. `--omit-body`: Omit saving the  parsed response body (`{"response": { ... "body": ... }}`) from the the (json)-output

### Describe the use case of this feature:

- The body responses blow up the output most
- The above mentioned implemented flags reduce the output file size effectively
- Thereby, the meta data (URL, status code, technologies) can be processed after spidering, without dealing with the huge body responses

**Comment by NotoriousRebel** [comment]
@maik-s Irregardless of customizable json output, are you able to get any json output at all?? `katana -list urls.txt -kf -c 4 -p 4 -jc -d 4 -header "User-Agent: user-agent" -timeout 60 -json -output katana_target_com_results_testing.json -nc -verbose` Doing that leads to the json output file not even being created. When JSON output gets fixed, allowing it to be customized is extremely important.

**Comment by maik-s** [comment]
Yes, I get json output, but as described not customisable and therefore it blows up very quickly.

In your case I have the following guess, why you don't retrieve output.
If it doesn't help, **please open a seperate issue** to keep this thread stick to the **original topic**.

You specify parameter `-kf`, which expects a string value (all, sitemap, robotstxt), which you don't supply. Thereby, I think the argument parser is confused for the consecutive arguments and the `json` option etc is not respected correctly.

**Comment by NotoriousRebel** [comment]
Eureka! You are very correct, for some reason I just assumed doing -kf would default to all which seems to be a bit more logical than how it's currently structured but that's okay! Now that is it settled, I wholeheartedly agree with your suggestions as they would be very useful for post processing katana JSON results!

**Comment by ehsandeep** [comment]
@maik-s thanks for adding this support; now included in the latest release - https://github.com/projectdiscovery/katana/releases/tag/v1.0.2

**Comment by maik-s** [comment]
Thanks for reviewing and merging this so quickly!
