### ISSUE TITLE
Katana does not parse textarea element

### ISSUE THREAD

**Issue by hczdmr** [projectdiscovery/katana#456]
### katana version:
v1.0.1

### Current Behavior:
I have a test.html file as below:

```
<form action="/targets/simple-textarea-form.html">
  <textarea type="text" name="textarea-get-form" id="textarea-get-form">default_value</textarea>
  <input type="submit" value="send" name="simple-textarea-form-submit-button">
</form>
```

Katana finds http://xxx.com/targets/simple-textarea-form.html?simple-textarea-form-submit-button=send 
URL instead of 
http://xxx.com/targets/simple-textarea-form.html?textarea-get-form=default_value&simple-textarea-form-submit-button=send
Because Katana can not parse textarea element.

### Expected Behavior:
I would expect Katana to find this URL: http://xxx.com/targets/simple-textarea-form.html?textarea-get-form=default_value&simple-textarea-form-submit-button=send

### Steps To Reproduce:
1. Run katana with this command: ./katana -u http://xxx.com/test.html -iqp -aff -sc -jc -kf all -hl -v -d 5
2. Katana finds this URL: http://xxx.com/targets/simple-textarea-form.html?simple-textarea-form-submit-button=send
3. I would expect Katana to find this URL: http://xxx.com/targets/simple-textarea-form.html?textarea-get-form=default_value&simple-textarea-form-submit-button=send

**Comment by olearycrew** [comment]
Looks like we're only looking for `input` type fields and not `textarea`s:

https://github.com/projectdiscovery/katana/blob/846693f096ee4bcb6e46963d1690ac966907ec0f/pkg/engine/parser/parser.go#L542

**Comment by hczdmr** [comment]
Yeah, you can add textareas if you want :)

**Comment by hczdmr** [comment]
@olearycrew Is it planned to be added as a feature? If you want we can develop this feature?

**Comment by olearycrew** [comment]
@hczdmr I think we would welcome a contribution here (cc @ehsandeep)

**Comment by Mzack9999** [comment]
Fixed in https://github.com/projectdiscovery/katana/pull/921
