### ISSUE TITLE
Extension Match (-em) has no effect

### ISSUE THREAD

**Issue by PatrikFehrenbach** [projectdiscovery/katana#480]
### katana version:

v1.0.2

### Current Behavior:

Due to the documentation, the `-em` flag allows to filter for certain file types, however it does not seem to have any effect:

When I run `katana -u https://blog.it-securityguard.com -jc -f ufile` it shows me all available files (including Javascript), howevern if I want to combine it with `-em js` it wouldn't filter properly. 

### Expected Behavior:

I would expect Katana to only display the available JS files

### Steps To Reproduce:
1. Run 'katana -u https://blog.it-securityguard.com -jc -f ufile'
2. See that there are Javascript files available
3. Run ' katana -u https://blog.it-securityguard.com -jc -f ufile -em js' and try to match only JS files
4. See that you don't get any output 

### Anything else:
![1](https://github.com/projectdiscovery/katana/assets/9072595/bcf92b52-d6f7-462c-b3c5-5f2ce5608c87)
![2](https://github.com/projectdiscovery/katana/assets/9072595/015bba1e-a25a-4ee9-982f-3302934163c3)

**Comment by ehsandeep** [comment]
@PatrikFehrenbach, thanks for opening this issue, I can confirm the issue; actually as of now `-em / -ef` is applied as scope to match or filter, Instead, it should be applied on the output and should be easy to fix.

For now, you can also make use of `-match-regex` option which is applied on output.

```
echo www.hackerone.com | katana -mr '^.*\.(js)$'
```

**Comment by PatrikFehrenbach** [comment]
@ehsandeep 

Thank you so much for quick response and the solution 🥇

**Comment by ehsandeep** [comment]
@PatrikFehrenbach, this is now fixed in the latest release; thanks again for reporting this.
