### ISSUE TITLE
Stored Response Path Not in JSON Output When Using "-sr" and "-jsonl" Flags

### ISSUE THREAD

**Issue by ErikOwen** [projectdiscovery/katana#530]
### katana version:

v1.0.2

### Current Behavior:

Katana is invoked with the "-jsonl" and "-sr" flags, and the path to the response body is not found in the JSON output, unlike [httpx](https://github.com/projectdiscovery/httpx).

### Expected Behavior:

A `stored_response_path` key is in the JSON output when "-sr" and "-json" flags are used, similar to [httpx](https://github.com/projectdiscovery/httpx).

### Steps To Reproduce:

1. Run katana with "-jsonl" and "-sr" flags:
 ```
 echo "https://www.google.com" | katana -d 1 -jsonl -sr
 ```
2. Notice how there **is no** "stored_response_path" key in the JSON for where the response body was saved to in the filesystem
3. Run httpx with `-json" and "-sr" flags:
 ```
 echo "https://www.google.com" | httpx -json -sr
 ```
4. Notice how there i**s** a "stored_response_path" key in the JSON for where the response body was saved to in the filesystem
### Anything else:

N/A

**Comment by ehsandeep** [comment]
@ErikOwen now available in the latest release.
