### ISSUE TITLE
cannot load katana

### ISSUE THREAD

**Issue by zerokeeper** [projectdiscovery/katana#555]
### katana version:
katana_1.0.3_macOS_amd64

### Current Behavior:
cannot run on mac 10.13.6 High Sierra.

### Expected Behavior:

```
dyld: cannot load 'katana' (load command 0x80000033 is unknown)
[1]    61381 abort      katana
```
### Steps To Reproduce:

just run
`katana or katana -h `

I think it  maybe not support High Sierra any more,but there are some people still use High Sierra.
Can you still continue to support it?

**Comment by fail-open** [comment]
What happens when you build it yourself on your system?

**Comment by zerokeeper** [comment]
Ok now, sorry to bother you!
