### ISSUE TITLE
Katana when used as library in hybrid mode, OnResult callback doesn't capture Request.Raw as expected

### ISSUE THREAD

**Issue by fc-selvino** [projectdiscovery/katana#562]
katana version: Current version: v1.0.3

### Current Behavior:
when used katana as library, with headless option ie in hybrid mode, the OnResult callback function doesn't capture request.Raw properly, Though the verbose logs show its a POST request the Raw part of the request is showing GET

see below for logs written from the OnResult callback

**hybrid** 

`[form] [POST] http://127.0.0.1:8088/WebGoat/login
time="2023-08-16T23:33:03+05:30" level=info msg="Raw Request &{POST http://127.0.0.1:8088/WebGoat/login  1 map[Content-Type:application/x-www-form-urlencoded] form action 127.0.0.1 http://127.0.0.1:8088/WebGoat map[] GET /WebGoat/login HTTP/1.1\r\nHost: 127.0.0.1:8088\r\nUser-Agent: Go-http-client/1.1\r\nAccept-Encoding: gzip\r\n\r\n}"`

I checked the same in the standard mode it gives proper result see bellow

`[form] [POST] http://127.0.0.1:8088/WebGoat/login [username=katana&password=katanaP@assw0rd1]
time="2023-08-16T23:44:12+05:30" level=info msg="Raw Request &{POST http://127.0.0.1:8088/WebGoat/login username=katana&password=katanaP@assw0rd1 1 map[Content-Type:application/x-www-form-urlencoded] form action 127.0.0.1 http://127.0.0.1:8088/WebGoat/login map[] POST /WebGoat/login HTTP/1.1\r\nHost: 127.0.0.1:8088\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36\r\nContent-Length: 41\r\nContent-Type: application/x-www-form-urlencoded\r\nAccept-Encoding: gzip\r\n\r\nusername=katana&password=katanaP@assw0rd1}"`

### Expected Behavior:
if the same POST request is intercepted in both hybrid and standard mode The raw request should be same or similar

**Comment by dogancanbakir** [comment]
@fc-selvino, could you please share the code example with us so we can reproduce the issue? Thanks.

**Comment by fc-selvino** [comment]
OnResult: func(result output.Result) { // Callback function to execute for result
			logger.Logger.Infof("Raw Request %v", result.Request)
			parsedURL, _ := url.Parse(result.Request.URL)
			baseURL := parsedURL.Scheme + "://" + parsedURL.Host
			...
		},

**Comment by dogancanbakir** [comment]
@fc-selvino, Could you please share the whole snippet? A single config can make a huge diff, thanks!

**Comment by dogancanbakir** [comment]
Closing this. Feel free to reopen if the issue persists.
