### ISSUE TITLE
issue generate when i install katana on windows 10

### ISSUE THREAD

**Issue by d4715** [projectdiscovery/katana#624]
i am using windows 10 and install latest go then i install katana but not install perfectly so please help me for this 
### katana version:
v1.0.4

### Current Behavior:
install process fail 

### Steps To Reproduce:
C:\Program Files\Go\bin>go install github.com/projectdiscovery/katana/cmd/katana@latest

and i got this 

github.com/smacker/go-tree-sitter/javascript: build constraints exclude all Go files in C:\Users\$$HumaL$$\go\pkg\mod\github.com\smacker\go-tree-sitter@v0.0.0-20220628134258-ac06e95cfa11\javascript
# github.com/smacker/go-tree-sitter
C:\Users\$$HumaL$$\go\pkg\mod\github.com\smacker\go-tree-sitter@v0.0.0-20220628134258-ac06e95cfa11\iter.go:17:18: undefined: Node
C:\Users\$$HumaL$$\go\pkg\mod\github.com\smacker\go-tree-sitter@v0.0.0-20220628134258-ac06e95cfa11\iter.go:21:21: undefined: Node
C:\Users\$$HumaL$$\go\pkg\mod\github.com\smacker\go-tree-sitter@v0.0.0-20220628134258-ac06e95cfa11\iter.go:25:20: undefined: Node
C:\Users\$$HumaL$$\go\pkg\mod\github.com\smacker\go-tree-sitter@v0.0.0-20220628134258-ac06e95cfa11\iter.go:30:26: undefined: Node
C:\Users\$$HumaL$$\go\pkg\mod\github.com\smacker\go-tree-sitter@v0.0.0-20220628134258-ac06e95cfa11\iter.go:34:20: undefined: Node
C:\Users\$$HumaL$$\go\pkg\mod\github.com\smacker\go-tree-sitter@v0.0.0-20220628134258-ac06e95cfa11\iter.go:38:32: undefined: Node
C:\Users\$$HumaL$$\go\pkg\mod\github.com\smacker\go-tree-sitter@v0.0.0-20220628134258-ac06e95cfa11\iter.go:43:9: undefined: Node
C:\Users\$$HumaL$$\go\pkg\mod\github.com\smacker\go-tree-sitter@v0.0.0-20220628134258-ac06e95cfa11\iter.go:46:18: undefined: Node
C:\Users\$$HumaL$$\go\pkg\mod\github.com\smacker\go-tree-sitter@v0.0.0-20220628134258-ac06e95cfa11\iter.go:68:40: undefined: Node

### Anything else:
attached screen shot 
![1](https://github.com/projectdiscovery/katana/assets/11803332/aad7ff28-a951-45a2-b781-9a8eca6ab584)

**Comment by dogancanbakir** [comment]
@d4715, thank you for bringing this to our attention. We are aware of the issue, which is [planned to be worked on](https://github.com/projectdiscovery/katana/issues/577). In the meantime, please install the `tree-sitter` [build dependencies](https://github.com/projectdiscovery/katana/pull/547/files) and try to install `katana` again. Let me know if you need any help!

**Comment by amiremami** [comment]
> @d4715, thank you for bringing this to our attention. We are aware of the issue, which is [planned to be worked on](https://github.com/projectdiscovery/katana/issues/577). In the meantime, please install the `tree-sitter` [build dependencies](https://github.com/projectdiscovery/katana/pull/547/files) and try to install `katana` again. Let me know if you need any help!

Can you please explain the solution more and step by step? I have same issue, thanks.

**Comment by jayateertha043** [comment]
Solution - 
1. Do these in admin cmd only - ```choco install zig```
2. Open another Admin cmd  and  - ```set CGO_ENABLED=1&set GOOS=windows&set GOARCH=amd64&set CC=zig cc&set CXX=zig c++```
3. Then do - ```go install github.com/projectdiscovery/katana/cmd/katana@latest```

Note: go-tree-sitter might show some warning when building, but it's fine ```katana -h``` after full install should work.

**Comment by amiremami** [comment]
> Solution -
> 
> 1. Do these in admin cmd only - `choco install zig`
> 2. Open another Admin cmd  and  - `set CGO_ENABLED=1&set GOOS=windows&set GOARCH=amd64&set CC=zig cc&set CXX=zig c++`
> 3. Then do - `go install github.com/projectdiscovery/katana/cmd/katana@latest`
> 
> Note: go-tree-sitter might show some warning when building, but it's fine `katana -h` after full install should work.

Thanks, how for linux ubuntu?

**Comment by d4715** [comment]
> Solution -
> 
>     1. Do these in admin cmd only - `choco install zig`
> 
>     2. Open another Admin cmd  and  - `set CGO_ENABLED=1&set GOOS=windows&set GOARCH=amd64&set CC=zig cc&set CXX=zig c++`
> 
>     3. Then do - `go install github.com/projectdiscovery/katana/cmd/katana@latest`
> 
> 
> Note: go-tree-sitter might show some warning when building, but it's fine `katana -h` after full install should work.

**Comment by d4715** [comment]
whenever I try to install zig via this command choco install zig i got these error 'choco' is not recognized as an internal or external command,
operable program or batch file.
you can check image
![2](https://github.com/projectdiscovery/katana/assets/11803332/5f450973-d3bb-42b5-9273-28d01ecabf64)
so now what to do

**Comment by Hamedhani9989** [comment]
1. Do these in admin cmd only - `choco install zig`

2. Open another Admin cmd  and  - `set CGO_ENABLED=1&set GOOS=windows&set GOARCH=amd64&set CC=zig cc&set CXX=zig c++`

3. Then do - `go install github.com/projectdiscovery/katana/cmd/katana@latest`

run all of these still no success

**Comment by mahirdzirlo** [comment]
issue still open
