### ISSUE TITLE
Empty headers with hybrid crawling in XHR requests

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/katana#639]
### katana version:
`main|dev`

### Current Behavior:
Empty XHR headers in hybrid crawling

### Expected Behavior:
Headers dumped correctly

### Steps To Reproduce:
Ref https://github.com/projectdiscovery/katana/pull/631#issue-1950321979

**Comment by Fly-Playgroud** [comment]
I want to say that there are still bugs in his handling of **ExtraHeaders**. Currently, it only captures part of the common request headers, not the complete request headers！！！！！
