### ISSUE TITLE
-known-files does not work with -depth 1 or -depth 2

### ISSUE THREAD

**Issue by cyal1** [projectdiscovery/katana#641]
-known-files does not work with -depth 1 or -depth 2

**Comment by cyal1** [comment]
katana version:
latest

**Comment by cyal1** [comment]
`katana -u https://remoteadvisor-east1.apple.com/ -hl --system-chrome  -xhr-extraction -kf all -depth 1 -aff -s breadth-first  -iqp -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"  -o /tmp/a.json`

**Comment by cyal1** [comment]
katana -u https://remoteadvisor-east1.apple.com/ -hl --system-chrome  -xhr-extraction -kf all -depth 2 -aff -s breadth-first  -iqp -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"  -o /tmp/a.json
result1
https://remoteadvisor-east1.apple.com/
https://remoteadvisor-east1.apple.com/content/access_key_input.js
https://remoteadvisor-east1.apple.com/content/portal.js
https://remoteadvisor-east1.apple.com/api/content/core.js
https://www.apple.com/ac/globalfooter/2.0/en_US/scripts/ac-globalfooter.built.js
https://remoteadvisor-east1.apple.com/api/start_session.js
https://remoteadvisor-east1.apple.com/content/lib/jquery.js
https://remoteadvisor-east1.apple.com/us/search?src=globalnav
https://www.apple.com/ac/globalfooter/2.0/en_US/styles/ac-globalfooter.built.css
https://images.apple.com/support/css/suggest2.css
https://images.apple.com/support/css/support.css
https://www.apple.com/ac/localnav/3.0/styles/ac-localnav.built.css
https://remoteadvisor-east1.apple.com/us/search
https://www.apple.com/ac/globalnav/2.0/en_US/styles/ac-globalnav.built.css
https://remoteadvisor-east1.apple.com/a
https://remoteadvisor-east1.apple.com/content/mobile.css
https://remoteadvisor-east1.apple.com/content/public.css
https://remoteadvisor-east1.apple.com/content/common.css
http://www.apple.com/sitemap/
http://www.apple.com
http://www.apple.com/us/shop/goto/help/sales_refunds
https://remoteadvisor-east1.apple.com/check_access_key
https://remoteadvisor-east1.apple.com/check_access_key?access_key_submit=Submit&access_key_pretty=katana
http://www.apple.com/legal/internet-services/terms/site.html
http://www.apple.com/us/search
http://www.apple.com/privacy/privacy-policy/
http://www.apple.com/legal/remotesupport/
https://remoteadvisor-east1.apple.com/content/portal-customizations.css?_c=0
http://www.apple.com/music/
http://www.apple.com/mac/
http://www.apple.com/support/
http://www.apple.com/us/shop/goto/bag
http://www.apple.com/watch/
http://www.apple.com/tv/
http://www.apple.com/iphone/
http://www.apple.com/ipad/


---
katana -u https://remoteadvisor-east1.apple.com/ -hl --system-chrome  -xhr-extraction -kf all -depth 3 -aff -s breadth-first  -iqp -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36"  -o /tmp/a.json
result2
https://remoteadvisor-east1.apple.com/appliance/
https://remoteadvisor-east1.apple.com/api/
https://remoteadvisor-east1.apple.com/
https://remoteadvisor-east1.apple.com/files/
...

result1 not contain `https://remoteadvisor-east1.apple.com/appliance/`,`https://remoteadvisor-east1.apple.com/files/`, this endpoint in https://remoteadvisor-east1.apple.com/robots.txt

**Comment by dogancanbakir** [comment]
@cyal1,
Thanks for providing additional info! The reason you don't see `/appliance` and `/files` is because we're setting the depth for the endpoints in the `robots.txt`:
https://github.com/projectdiscovery/katana/blob/3558f38f8546f9ecc064c6c647fddd097c05bed7/pkg/engine/parser/files/robotstxt.go#L50

And this is where we exclude it:
https://github.com/projectdiscovery/katana/blob/3558f38f8546f9ecc064c6c647fddd097c05bed7/pkg/engine/common/base.go#L81

I'll let you know about the decision to change this behavior.

**Comment by Mzack9999** [comment]
The depth property identifies at which nesting level the item is found and visited. The `http://URL/robots.txt` and `http://URL/sitemap.xml` are located at nesting level 1 (whereas the root `http://URL` is at level 0). Hence any URLs found and later crawled in such files will happen at nesting level 2. In case you specify a nesting level 0 or 1 it means that no URL equal or above this threshold of nesting will be visited. Probably what we can do is to add a note in the readme file that a depth level of at least 3 is expected if the `kf/known-files` option is used or increase it automatically with a clear console message

**Comment by cyal1** [comment]
hello, In case you specify a nesting level 2 also don't see /appliance and /files

> katana -u https://remoteadvisor-east1.apple.com/ -hl --system-chrome -xhr-extraction -kf all -depth 2 -aff -s breadth-first -iqp -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" -o /tmp/a.json result1 https://remoteadvisor-east1.apple.com/ https://remoteadvisor-east1.apple.com/content/access_key_input.js https://remoteadvisor-east1.apple.com/content/portal.js https://remoteadvisor-east1.apple.com/api/content/core.js https://www.apple.com/ac/globalfooter/2.0/en_US/scripts/ac-globalfooter.built.js https://remoteadvisor-east1.apple.com/api/start_session.js https://remoteadvisor-east1.apple.com/content/lib/jquery.js https://remoteadvisor-east1.apple.com/us/search?src=globalnav https://www.apple.com/ac/globalfooter/2.0/en_US/styles/ac-globalfooter.built.css https://images.apple.com/support/css/suggest2.css https://images.apple.com/support/css/support.css https://www.apple.com/ac/localnav/3.0/styles/ac-localnav.built.css https://remoteadvisor-east1.apple.com/us/search https://www.apple.com/ac/globalnav/2.0/en_US/styles/ac-globalnav.built.css https://remoteadvisor-east1.apple.com/a https://remoteadvisor-east1.apple.com/content/mobile.css https://remoteadvisor-east1.apple.com/content/public.css https://remoteadvisor-east1.apple.com/content/common.css http://www.apple.com/sitemap/ http://www.apple.com http://www.apple.com/us/shop/goto/help/sales_refunds https://remoteadvisor-east1.apple.com/check_access_key https://remoteadvisor-east1.apple.com/check_access_key?access_key_submit=Submit&access_key_pretty=katana http://www.apple.com/legal/internet-services/terms/site.html http://www.apple.com/us/search http://www.apple.com/privacy/privacy-policy/ http://www.apple.com/legal/remotesupport/ https://remoteadvisor-east1.apple.com/content/portal-customizations.css?_c=0 http://www.apple.com/music/ http://www.apple.com/mac/ http://www.apple.com/support/ http://www.apple.com/us/shop/goto/bag http://www.apple.com/watch/ http://www.apple.com/tv/ http://www.apple.com/iphone/ http://www.apple.com/ipad/
> 
> katana -u https://remoteadvisor-east1.apple.com/ -hl --system-chrome -xhr-extraction -kf all -depth 3 -aff -s breadth-first -iqp -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" -o /tmp/a.json result2 https://remoteadvisor-east1.apple.com/appliance/ https://remoteadvisor-east1.apple.com/api/ https://remoteadvisor-east1.apple.com/ https://remoteadvisor-east1.apple.com/files/ ...
> 
> result1 not contain `https://remoteadvisor-east1.apple.com/appliance/`,`https://remoteadvisor-east1.apple.com/files/`, this endpoint in https://remoteadvisor-east1.apple.com/robots.txt

**Comment by Mzack9999** [comment]
A nesting level equals to 2 unfortunately still prevents them from being visited (see the condition at https://github.com/projectdiscovery/katana/blob/3558f38f8546f9ecc064c6c647fddd097c05bed7/pkg/engine/common/base.go#L81

@dogancanbakir I'd propose to increment the max depth to 3 if `-kf/-known-files` are used. This implies the following changes:
- Add a note to docs that nesting level 3 is required with known files option
- Auto-Increase level to 3 with an informative message to user if the flag is used

What do you think?
