### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x11bd833]

### ISSUE THREAD

**Issue by defaul0t** [projectdiscovery/katana#643]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x11bd833]

1f9b5290080\"\u003edocument.getElementById(\"back\").addEventListener(\"click\", function(e){ history.go(-1); e.preventDefault(); });\u003c/script\u003e\u003c/div\u003e\u003c/div\u003e\u003c/body\u003e\u003c/html\u003e"}}
{"timestamp":"2023-10-28T02:57:36.998509777Z","request":{"method":"GET","endpoint":"https://servicespartnerportal.dell.com/assets/ajax/src.php","tag":"html","attribute":"regex","source":"https://servicespartnerportal.dell.com/assets/portal-fe748dd1ae8b9853a50756a641f45c57.js","raw":"GET /assets/ajax/src.php HTTP/1.1\r\nHost: servicespartnerportal.dell.com\r\nUser-Agent: Go-http-client/1.1\r\nAccept-Encoding: gzip\r\n\r\n"},"error":"[hybrid:RUNTIME] context deadline exceeded \u003c- could not get dom"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x11bd833]

goroutine 15287 [running]:
github.com/projectdiscovery/retryablehttp-go.FromRequest(0x0)
        /home/runner/go/pkg/mod/github.com/projectdiscovery/retryablehttp-go@v1.0.26/request.go:176 +0x73
github.com/projectdiscovery/katana/pkg/engine/hybrid.(*Crawler).navigateRequest.func1(0xc0020605a0)
        /home/runner/work/katana/katana/pkg/engine/hybrid/crawl.go:89 +0x679
github.com/projectdiscovery/katana/pkg/engine/hybrid.(*Hijack).Start.func2(0x0?)
        /home/runner/work/katana/katana/pkg/engine/hybrid/hijack.go:52 +0x2f
reflect.Value.call({0x12ccd60?, 0xc002aa1cf8?, 0x100c00223de40?}, {0x14afb83, 0x4}, {0xc00223df58, 0x1, 0xc0020605a0?})
        /opt/hostedtoolcache/go/1.20.7/x64/src/reflect/value.go:586 +0xb0b
reflect.Value.Call({0x12ccd60?, 0xc002aa1cf8?, 0xc0020605a0?}, {0xc00223df58?, 0x6945476468526d49?, 0x734a434c39746e4f?})
        /opt/hostedtoolcache/go/1.20.7/x64/src/reflect/value.go:370 +0xbc
github.com/go-rod/rod.(*Browser).eachEvent.func1()
        /home/runner/go/pkg/mod/github.com/go-rod/rod@v0.114.1/browser.go:401 +0x412
github.com/projectdiscovery/katana/pkg/engine/hybrid.(*Hijack).Start.func3()
        /home/runner/work/katana/katana/pkg/engine/hybrid/hijack.go:57 +0x25
created by github.com/projectdiscovery/katana/pkg/engine/hybrid.(*Crawler).navigateRequest
        /home/runner/work/katana/katana/pkg/engine/hybrid/crawl.go:49 +0x51c
root@C20230501105875:~/kahta# ./katana -list url.txt -headless -no-sandbox -tlsi -jc -aff  -iqp -d 9 -kf robotstxt,sitemapxml  -nc  -j -o bu.json  -f qurl  -fr "\/[0-9]{7,}\/"g":"html","attribute":"regex","source":"https://servicespartnerportal.dell.com/assets/portal-fe748dd1ae8b9853a50756a641f45c57.js","raw":"GET /assets/ajax/src.php HTTP/1.1\r\nHost: servicespartnerportal.dell.com\r\nUser-Agent: Go-http-client/1.1\r\nAccept-Encoding: gzip\r\n\r\n"},"error":"[hybrid:RUNTIME] context deadline exceeded \u003c- could not get dom"}

**Comment by dogancanbakir** [comment]
@defaul0t,
Thanks for letting us know. Can you provide the required steps to reproduce the issue? cmd etc.

**Comment by dogancanbakir** [comment]
Closing this. Feel free to reopen if the issue persists.
