### ISSUE TITLE
katana not working on Ubuntu 20.04.6 LTS

### ISSUE THREAD

**Issue by d4715** [projectdiscovery/katana#678]
### Discussed in https://github.com/projectdiscovery/katana/discussions/677

<div type='discussions-op-text'>

<sup>Originally posted by **d4715** November 29, 2023</sup>
Hello There,

i want install tool called katana from project discovery but i can't 
i have to manually install this tool when i install tool manually so i download and copy katana file in [/root/go/bin/
![katana](https://github.com/projectdiscovery/katana/assets/11803332/53005d56-c8ed-4269-8089-94b8c4a83740)

then i just type this command katana --help i got these error   
(i attached screen shot)
katana: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by katana)
katana: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by katana)

i am using ubuntu (as a rdp server)
Distributor ID:	Ubuntu
Description:Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

so please help me out for this issues 

thanks</div>

**Comment by dogancanbakir** [comment]
@d4715,  could you update/install the required `glibc` version mentioned in the error message? You can check the current version by running `ldd --version`. Let us know if it works for you!

**Comment by lostin21st** [comment]
> @d4715, could you update/install the required `glibc` version mentioned in the error message? You can check the current version by running `ldd --version`. Let us know if it works for you!
hello, I encountered the same problem
<img width="776" alt="image" src="https://github.com/projectdiscovery/katana/assets/19514272/1a8d05e6-ac24-4a52-a24d-4baae8626c7d">
this my lld version: ldd (Debian GLIBC 2.28-10+deb10u2) 2.28
<img width="608" alt="image" src="https://github.com/projectdiscovery/katana/assets/19514272/8ad16c67-a7ce-4e23-b31f-133460f89b60">

**Comment by d4715** [comment]
Hello there,
all done i just update and all done
sorry for late reply

Thanks,
FROM ,
DHRUV MANKAD
PHONE NO  +919824670424
EMAIL ID : ***@***.***

**Comment by dogancanbakir** [comment]
Closing this, thanks for the update!

**Comment by xnl-h4ck3r** [comment]
Hi @lostin21st and @d4715, I have the same problem. What steps do you take to install glibc 2.32 and 2.34? Many thanks

**Comment by xnl-h4ck3r** [comment]
Thanks @blackcodersec
