### ISSUE TITLE
对特定防护网站的绕过

### ISSUE THREAD

**Issue by moyuwa** [projectdiscovery/katana#694]
我想要先通过chrome浏览器图形化访问目标网站，在指定时间或匹配到某个字段（请求头或内容）后，提取（最后一次）请求的请求包头的认证信息（用于绕过反爬保护），再通过工具的请求快速爬取，而不是全程通过chrome浏览器访问。

nuclei有类似的工作流参数，katana可以实现吗？

**Comment by Mzack9999** [comment]
Probably you can accomplish the result by performing the initial http authentication via nuclei headless and then invoking katana for crawling through code templates (that can run external tools). I was unable to find them on hosted version, but the original markdown is available at `https://github.com/projectdiscovery/docs/blob/main/templates/protocols/code.mdx`

**Comment by Mzack9999** [comment]
Closing as not planned - Out of scope of katana project
