### ISSUE TITLE
Katana Library: OutputMatchRegex & OutputFilterRegex not functioning as expected

### ISSUE THREAD

**Issue by iamnihal** [projectdiscovery/katana#716]
### Current Behavior:
I'm running Katana as a library. The issue is when `OutputMatchRegex` & `OutputFilterRegex` [flags](https://github.com/projectdiscovery/katana/blob/3558f38f8546f9ecc064c6c647fddd097c05bed7/pkg/types/options.go#L132C1-L134C39) are passed to `Option` struct, it's not working as expected.

After going through the code, I encountered that methods `matchOutput` and `filterOutput` are responsible for performing the match/filter activity but it's attached to [`StandardWriter`](https://github.com/projectdiscovery/katana/blob/3558f38f8546f9ecc064c6c647fddd097c05bed7/pkg/output/output.go#L254C1-L289C2) struct  and I found no way to invoke these methods when using Katana as library. Hence, these two methods are not working as expected.

### Expected Behavior:

`OutputMatchRegex` & `OutputFilterRegex` fields when passed to the `Option` struct should work as expected i.e., should match/filter the output based on RegEx passed into it.

### Steps To Reproduce:
I'm using [katana](https://github.com/projectdiscovery/katana/tree/dev#katana-as-a-library) as library code:
```
package main

import (
	"math"

	"github.com/projectdiscovery/gologger"
	"github.com/projectdiscovery/katana/pkg/engine/standard"
	"github.com/projectdiscovery/katana/pkg/output"
	"github.com/projectdiscovery/katana/pkg/types"
)

func main() {
	options := &types.Options{
		MaxDepth:          3,           // Maximum depth to crawl
		FieldScope:        "rdn",       // Crawling Scope Field
		BodyReadSize:      math.MaxInt, // Maximum response size to read
		Timeout:           10,          // Timeout is the time to wait for request in seconds
		Concurrency:       10,          // Concurrency is the number of concurrent crawling goroutines
		OutputMatchRegex:  []string{"policies"},
		Parallelism:       10,            // Parallelism is the number of urls processing goroutines
		Delay:             0,             // Delay is the delay between each crawl requests in seconds
		RateLimit:         150,           // Maximum requests to send per second
		Strategy:          "depth-first", // Visit strategy (depth-first, breadth-first)
		OnResult: func(result output.Result) { // Callback function to execute for result
			gologger.Info().Msg(result.Request.URL)
		},
	}
	crawlerOptions, err := types.NewCrawlerOptions(options)
	if err != nil {
		gologger.Fatal().Msg(err.Error())
	}
	defer crawlerOptions.Close()
	crawler, err := standard.New(crawlerOptions)
	if err != nil {
		gologger.Fatal().Msg(err.Error())
	}
	defer crawler.Close()
	var input = "https://www.hackerone.com"
	err = crawler.Crawl(input)
	if err != nil {
		gologger.Warning().Msgf("Could not crawl %s: %s", input, err.Error())
	}
}
```
The expected output of the program should only include URLs containing the word "**policies**", but it currently provides all URLs regardless of the specified Regex.

Let me know if any additional details are required. I'm happy to provide them.

**Comment by dogancanbakir** [comment]
Thanks for opening the issue. While we're working on a fix, you can use the following workaround: `OutputMatchCondition: "contains(endpoint, 'policies')"`.
