### ISSUE TITLE
-mdc and -fdc options do not work.

### ISSUE THREAD

**Issue by Nzoth9** [projectdiscovery/katana#725]
Hi, I'm using the following options. `-mdc 'status_code == 200' -fdc "contains(body, 'refresh')"`

The expected result is ignored if the response code is not `200` or the `refresh` string is contained within the content being responded to. but it doesn't work. (katana version is v1.0.4)

have a great day!

**Comment by dogancanbakir** [comment]
Thanks for opening the issue. I tried with scanme.sh and it's working:

the response we get each request:
```console
cat katana_response/scanme.sh/15c54a7d479109d03421bebc2860bcf1a4b0a342.txt 
https://scanme.sh


GET / HTTP/1.1
Host: scanme.sh
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Accept-Encoding: gzip



HTTP/1.1 200 OK
Content-Length: 2
Content-Type: text/plain; charset=utf-8
Date: Fri, 12 Jan 2024 12:16:47 GMT

ok
```

status code and body is matched, so it's filtered out by `-fdc`:
```console
$ go run . -u scanme.sh -mdc 'status_code == 200' -fdc 'contains(body, "ok")' -silent

```

status code is matched but body is not matched, so it's not filtered out by `-fdc`:
```console
$ go run . -u scanme.sh -mdc 'status_code == 200' -fdc 'contains(body, "dummy")' -silent
https://scanme.sh

```

Let us know if you have further questions!

**Comment by dogancanbakir** [comment]
In my case, above, it works both with `-headless` and without it. Can you please provide the exact repro steps? You can always DM us on Discord if you're uncomfortable sharing them here -target, for example.

**Comment by dogancanbakir** [comment]
The given URL wasn't reachable; I couldn't test it.
