### ISSUE TITLE
Output file not created when using -kf option

### ISSUE THREAD

**Issue by 99smith** [projectdiscovery/katana#765]
the command : katana -list xyz.com.txt  -jc -kf -cs xyz.com -o xyz.katana

will not create output file xyz.katana

but if we will remove -kf option the output file will be created ..

katana -list xyz.com.txt  -jc -cs xyz.com -o xyz.katana

**Comment by dogancanbakir** [comment]
When using the `-kf` flag, please ensure that you provide one of the following options:
```
   -kf, -known-files string      enable crawling of known files (all,robotstxt,sitemapxml), a minimum depth of 3 is required to ensure all known files are properly crawled.
```

- all
- robotstxt
- sitemapxml
