### ISSUE TITLE
404 Filter not works

### ISSUE THREAD

**Issue by amiremami** [projectdiscovery/katana#766]
Hi, I have several issues with Katana.

katana -u domain.com -o katana.txt -headless --no-sandbox -silent -jc -jsl -kf robotstxt,sitemapxml -cos feed,css,mailto -fdc 'status_code == 404' -proxy socks5://username:password@proxyhostname:port

1. I'm using this command, however, in the output file, there are many 404 links. But I used -fdc 'status_code == 404' to not show them.

![image](https://github.com/projectdiscovery/katana/assets/15929497/9cce3f89-fc9b-4141-8a26-8dbed2ad5f3d)

2. When I use proxy, it's not finding any link at all. Only prints the domain.

![image](https://github.com/projectdiscovery/katana/assets/15929497/1cee8a5b-749f-4793-99bd-743b9d3c8f97)

3. When I use headless, my cpu is 100% all the time, and if it finds many links, I mean such as 100, then my vps will be down with 2 dedicated vcpu and 4 gb ram.

4. And, with the same command, katana gives me different results. For example, in one test, it shows me 10 links, In next test it gives me 50. 

![image](https://github.com/projectdiscovery/katana/assets/15929497/d5c0215e-2164-4f9e-9268-366bcc931e27)

As you can see in the image, with same command, first it gave me 2 domains, then it gave me a lot.

### katana version: 1.0.5

Thanks

**Comment by dogancanbakir** [comment]
Could you please try again with a longer timeout? `-timeout`
