### ISSUE TITLE
Make go-tree-sitter optional on unsupported 386 machines

### ISSUE THREAD

**Issue by mb01LINX** [projectdiscovery/katana#790]
Architectures based on 386 such as CentOS, prevent the binary from being correctly built due to go-tree-sitter cgo constraints. The dependency should be optional via conditional compilation.

**Comment by Mzack9999** [comment]
@mb01LINX Thanks for opening the issue. I've modified it with more details related to the issue.

**Comment by mb01LINX** [comment]
Hallo @Mzack9999 Thank you for developing this tool. and can't wait for release of the executable for the 386 architecture. Warm regards.:D

**Comment by mb01LINX** [comment]
Hello there! Thanks to this, we can now enjoy the 386 executable. 


:BestRegards!~
