### ISSUE TITLE
GLIBC version requerd

### ISSUE THREAD

**Issue by djallalzoldik** [projectdiscovery/katana#805]
I update the tool to the latest version and i have this issues,
katana: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by katana)
katana: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by katana)

**Comment by dogancanbakir** [comment]
For solution please refer to https://github.com/projectdiscovery/katana/issues/678. Closing this.
