### ISSUE TITLE
Crawling for thispage.domain.com

### ISSUE THREAD

**Issue by pjbish** [projectdiscovery/katana#806]
Hi.

This is a great tool for finding pages like this

domain.com/thispage

Is there a parameter that can be used to find pages like this 

thispage.domain.com

I've tried a few things, and can't seem to work this one out. Can the tool do this ? If so, could you please provide the syntax.

Thanks.

Loving your work.

**Comment by dogancanbakir** [comment]
Thanks for opening this issue. Have you tried https://github.com/projectdiscovery/katana?tab=readme-ov-file#-field-scope?

**Comment by pjbish** [comment]
Thanks. That didn't find what I'm looking for. Still seemed to trawl domain/thispage

**Comment by dogancanbakir** [comment]
I understand. Can you please share the things you've tried so far and an example of what you want to achieve?

**Comment by pjbish** [comment]
I've tried all the options in that section

katana -u https://example.com -fs dn
katana -u https://example.com -fs fqdn
katana -u https://example.com -fs rdn

None of them found thispage.example.com which I know is there on my site

**Comment by dogancanbakir** [comment]
This is unclear. Do you want katana to crawl only subdomains or include them? Also, as much as we want katana to crawl everything properly, given the web's non-deterministic nature, things can be missed. Also, if you're not comfortable sharing your repro steps here, you can reach out over Discord.

**Comment by dogancanbakir** [comment]
Closing this. Feel free to reopen if the issue persists.
