### ISSUE TITLE
Adding urlscan passive sources is recommended

### ISSUE THREAD

**Issue by pwnhxl** [projectdiscovery/katana#842]
reference:
https://github.com/lc/gau/blob/update/pkg/providers/urlscan/urlscan.go

**Comment by GeorginaReeder** [comment]
Thanks for this suggestion @pwnhxl , we'll take a look into it!

**Comment by dogancanbakir** [comment]
Closing this. Reason: https://github.com/projectdiscovery/katana/pull/899

**Comment by dogancanbakir** [comment]
We have released the tool! Check it out here: https://github.com/projectdiscovery/urlfinder 🎉
