### ISSUE TITLE
issue on -passive feature

### ISSUE THREAD

**Issue by zy9ard3** [projectdiscovery/katana#892]
Hey @projectdiscovery team,

There seems to be an issue with the `-passive` flag, which doesn't seem to be working as expected. When we use the `-passive` flag with Katana, the crawler is supposed to perform standard crawling along with additional passive endpoints. However, what is happening now is that the crawler only looks for passive endpoints and exits if no passive endpoints are found

### Current Behavior :

When we use the `-passive` flag with Katana, the crawler only looks for passive endpoints and exits if none are found, without performing standard crawling on the given domain

### Expected Behavior :

The crawler should always perform standard crawling regardless of the flag. If the `-passive` flag is given, the crawler should include additionally fetched endpoints from passive sources and perform crawling on those along with the standard crawling

### Steps To Reproduce :

Take any random live host that does not have any passive URLs data in archives and execute the following two commands. You will notice the issue :

* `katana -u https://xyz.com -passive`

* `katana -u https://xyz.com`

#### Reference from my Side :

<img width="1920" alt="katana issue" src="https://github.com/projectdiscovery/katana/assets/67743789/c0dd98d2-2074-447a-812a-9bdceed37e6f">

*Kindly please rectify this issue for more efficient crawling*

Have a Great Day : )

Thanks & Regards,
@zy9ard3

**Comment by ehsandeep** [comment]
@zy9ard3 this is intended bheavior, passive + active crawling not meant to used togather, otherwise katana will spend hours to just resolve / filter thousand of dead urls from passive source.

```
katana -passive -headless -u example.com

   __        __                
  / /_____ _/ /____ ____  ___ _
 /  '_/ _  / __/ _  / _ \/ _  /
/_/\_\\_,_/\__/\_,_/_//_/\_,_/							 

		projectdiscovery.io

[FTL] could not create runner: [:RUNTIME] could not validate options <- [:RUNTIME] headless mode (-headless) and passive mode (-passive) cannot be used together
```

**Comment by dogancanbakir** [comment]
[[v]()](https://github.com/projectdiscovery/katana/pull/899)

**Comment by dogancanbakir** [comment]
We have released the tool! Check it out here: https://github.com/projectdiscovery/urlfinder 🎉
