### ISSUE TITLE
扫描大量url卡住，需要手动kill chrme线程

### ISSUE THREAD

**Issue by eeeeeeeeee-code** [projectdiscovery/katana#917]
使用的命令   -headless -no-sandbox -list url.txt -jc -kf robotstxt,sitemapxml -aff，使用的时候经常会卡住不动，一直不动的那种，查看是存在大量chrme线程没有结束导致，需要自己结束所有chrome线程 pkill -9 chrome  才能继续运行
```[tasklist]
### Tasks
```

**Comment by dogancanbakir** [comment]
translate:

The command -headless -no-sandbox -list url.txt -jc -kf robotstxt,sitemapxml -aff, when using the time will often be stuck in motion, has not been moving that kind of view is the existence of a large number of chrome thread did not end resulting in the need to end all the chrome threads themselves! pkill -9 chrome in order to continue to run

**Comment by dogancanbakir** [comment]
@eeeeeeeeee-code Can you add all the details so we can reproduce the issue? Thanks


```
<!-- 
1. Please search to see if an issue already exists for the bug you encountered.
2. For support requests, FAQs or "How to" questions, please use the GitHub Discussions section instead - https://github.com/projectdiscovery/katana/discussions or
3. Join our discord server at https://discord.gg/projectdiscovery and post the question on the #katana channel.
-->

<!-- ISSUES MISSING IMPORTANT INFORMATION MAY BE CLOSED WITHOUT INVESTIGATION. -->

### katana version:
<!-- You can find current version of katana with "katana -version" -->
<!-- We only accept issues that are reproducible on the latest version of katana. -->
<!-- You can find the latest version of project at https://github.com/projectdiscovery/katana/releases/ -->

### Current Behavior:
<!-- A concise description of what you're experiencing. -->

### Expected Behavior:
<!-- A concise description of what you expected to happen. -->

### Steps To Reproduce:
<!--
Example: steps to reproduce the behavior:
1. Run 'katana ..'
2. See error...
-->


### Anything else:
<!-- Links? References? Screnshots? Anything that will give us more context about the issue that you are encountering! -->
```

**Comment by eeeeeeeeee-code** [comment]
I have encountered this issue several times, but I thought github had this issue, so I did not record it.  When I meet it again recently, I will write a detailed issue

**Comment by dogancanbakir** [comment]
Closing this for now. Please let us know if you encounter this issue again with more details. Thank you!
